// Live regression check for the Taskpad Suite, against docs/taskpad_suite_requirements.md.
// Run: MCP_AUTH_TOKEN=... npm run test:live
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { readFile, writeFile, readdir } from "node:fs/promises";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import path from "node:path";

const BASE = process.env.PUBLIC_BASE_URL ?? "https://taskpad.duckdns.org";
const TOKEN = process.env.MCP_AUTH_TOKEN;
const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REQUIREMENTS_DOC = path.join(
  SCRIPT_DIR,
  "..",
  "docs",
  "taskpad_suite_requirements.md"
);
const VAULT_DIR = path.join(homedir(), "taskpad-vault");
const SYNC_DIR = path.join(VAULT_DIR, "notes");
const CONTEXT_DIR = path.join(VAULT_DIR, "context");
const SYNC_MARKER = "Auto-generated by Taskpad sync";

const TEST_PROJECT = "_taskpad_test";
const TEST_NOTE_TITLE = "healthcheck";

type Status = "PASS" | "FAIL" | "SKIP";
const results: { id: string; status: Status; detail: string }[] = [];

function record(id: string, status: Status, detail: string) {
  results.push({ id, status, detail });
  console.log(`[${status}] ${id} — ${detail}`);
}

async function main() {
  if (!TOKEN) {
    console.error("MCP_AUTH_TOKEN is not set. Export it and rerun.");
    process.exit(1);
  }

  const transport = new StreamableHTTPClientTransport(new URL(`${BASE}/mcp`), {
    requestInit: { headers: { Authorization: `Bearer ${TOKEN}` } },
  });
  const client = new Client({ name: "taskpad-test", version: "0.1.0" });
  await client.connect(transport);

  async function callTool(name: string, args: Record<string, unknown> = {}) {
    const res = await client.callTool({ name, arguments: args });
    const text = (res.content as { type: string; text?: string }[])
      .map((c) => c.text ?? "")
      .join("\n");
    if (res.isError) throw new Error(text);
    return text;
  }

  // R1
  try {
    const out = await callTool("list_projects");
    const projects = out.split("\n").filter(Boolean);
    projects.length > 0
      ? record("R1", "PASS", `${projects.length} project(s): ${projects.join(", ")}`)
      : record("R1", "FAIL", "list_projects returned no projects");
    var liveProjects = projects;
  } catch (err) {
    record("R1", "FAIL", String(err));
    var liveProjects: string[] = [];
  }

  const marker = `healthcheck-${new Date().toISOString()}`;

  // R2 + R6 (create_project idempotency, exercised via the same fixed test project)
  try {
    await callTool("create_project", { project: TEST_PROJECT });
    await callTool("create_project", { project: TEST_PROJECT }); // second call, must not error
    record("R6", "PASS", "create_project is idempotent on an existing project");
  } catch (err) {
    record("R6", "FAIL", String(err));
  }

  try {
    await callTool("save_note", {
      project: TEST_PROJECT,
      title: TEST_NOTE_TITLE,
      content: marker,
    });
    const fetched = await callTool("get_note", {
      project: TEST_PROJECT,
      title: TEST_NOTE_TITLE,
    });
    fetched.includes(marker)
      ? record("R2", "PASS", "save_note -> get_note round-trip matched")
      : record("R2", "FAIL", `get_note did not contain marker; got: ${fetched.slice(0, 200)}`);
  } catch (err) {
    record("R2", "FAIL", String(err));
  }

  // R3
  try {
    const scoped = await callTool("list_notes", { project: TEST_PROJECT });
    const all = await callTool("list_notes");
    scoped.includes(TEST_NOTE_TITLE) && all.length > 0
      ? record("R3", "PASS", "list_notes works scoped and unscoped")
      : record("R3", "FAIL", `scoped/all mismatch; scoped="${scoped}"`);
  } catch (err) {
    record("R3", "FAIL", String(err));
  }

  // R4
  try {
    const found = await callTool("search_notes", { query: marker, project: TEST_PROJECT });
    found.includes(TEST_NOTE_TITLE) || found.includes(marker)
      ? record("R4", "PASS", "search_notes found the marker note")
      : record("R4", "FAIL", `search_notes missed it; got: ${found.slice(0, 200)}`);
  } catch (err) {
    record("R4", "FAIL", String(err));
  }

  // R5
  try {
    const doc = await callTool("get_project_all_notes", { project: TEST_PROJECT });
    doc.includes(marker)
      ? record("R5", "PASS", "get_project_all_notes included the marker note")
      : record("R5", "FAIL", `combined doc missing marker; got: ${doc.slice(0, 200)}`);
  } catch (err) {
    record("R5", "FAIL", String(err));
  }

  // R7 / R11 / R12 / R14 — need shell access to the VPS or Home Server. Reported as
  // SKIP rather than silently passing; run by hand per docs/taskpad_suite_requirements.md.
  record("R7", "SKIP", "backup freshness needs Home Server file access (unreachable off-LAN)");
  record("R11", "SKIP", "restore rehearsal is a manual VPS procedure — see requirements doc");
  record("R12", "SKIP", "VPS cron check requires shell access to the VPS");
  record("R14", "SKIP", "Postgres port check requires shell access to the VPS");

  // R8
  try {
    const files = await readdir(SYNC_DIR);
    const localProjects = files
      .filter((f) => f.endsWith(".md"))
      .map((f) => f.slice(0, -3))
      .sort();
    const liveSet = [...liveProjects].sort();
    const missing = liveSet.filter((p) => !localProjects.includes(p));
    const orphans = localProjects.filter((p) => !liveSet.includes(p) && p !== TEST_PROJECT);
    missing.length === 0 && orphans.length === 0
      ? record("R8", "PASS", `local sync matches live projects (${localProjects.length} files)`)
      : record(
          "R8",
          "FAIL",
          `missing locally: [${missing.join(", ")}], orphaned locally: [${orphans.join(", ")}]`
        );
  } catch {
    record("R8", "SKIP", `${SYNC_DIR} doesn't exist — run the taskpad-notes-sync Skill first`);
  }

  // R9 — §8b's core guarantee: no sync/export job may ever write into context/.
  // A file bearing the sync marker there is proof one did.
  try {
    // recursive:true returns paths relative to CONTEXT_DIR (stable since Node 20.1)
    const entries = await readdir(CONTEXT_DIR, { recursive: true });
    const mdFiles = entries.filter((e) => e.endsWith(".md"));
    const polluted: string[] = [];
    for (const rel of mdFiles) {
      const head = (await readFile(path.join(CONTEXT_DIR, rel), "utf8")).slice(0, 200);
      if (head.includes(SYNC_MARKER)) polluted.push(rel);
    }
    polluted.length === 0
      ? record("R9", "PASS", `context/ clean — no sync-generated files (${mdFiles.length} .md checked)`)
      : record("R9", "FAIL", `sync job wrote into context/: ${polluted.join(", ")}`);
  } catch {
    record("R9", "SKIP", `${CONTEXT_DIR} doesn't exist yet`);
  }

  // R10 — vault must not have a public remote (holds a DB dump + employer-internal notes)
  try {
    const { execFileSync } = await import("node:child_process");
    const remotes = execFileSync("git", ["-C", VAULT_DIR, "remote", "-v"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!remotes) {
      record("R10", "PASS", "vault has no git remote (local-only)");
    } else {
      record("R10", "FAIL", `vault has a remote — verify it is private: ${remotes.split("\n")[0]}`);
    }
  } catch {
    record("R10", "SKIP", `${VAULT_DIR} is not a git repo yet`);
  }

  // R13 — /api/pad must not be reachable publicly (Execution 1 Block 5 hardening)
  try {
    const res = await fetch(`${BASE}/api/pad`, { method: "GET" });
    res.status === 404 || res.status === 403
      ? record("R13", "PASS", `/api/pad blocked at the edge (HTTP ${res.status})`)
      : record("R13", "FAIL", `/api/pad reachable from the public internet (HTTP ${res.status})`);
  } catch {
    record("R13", "PASS", "/api/pad not reachable (connection refused/no route)");
  }

  await client.close();
  await updateRequirementsDoc();

  const failed = results.filter((r) => r.status === "FAIL").length;
  console.log(`\n${results.length - failed}/${results.length} passed (excluding skips counted as neither)`);
  process.exit(failed > 0 ? 1 : 0);
}

async function updateRequirementsDoc() {
  const now = new Date().toISOString();
  const passed = results.filter((r) => r.status === "PASS").length;
  const failed = results.filter((r) => r.status === "FAIL").length;
  const skipped = results.filter((r) => r.status === "SKIP").length;
  const summaryLine = `<!-- LAST_RUN --> **Last run:** ${now} — ${passed} passed, ${failed} failed, ${skipped} skipped.`;
  const logLine =
    `- ${now}: ${passed} passed, ${failed} failed, ${skipped} skipped — ` +
    results.map((r) => `${r.id}=${r.status}`).join(" ");

  let doc: string;
  try {
    doc = await readFile(REQUIREMENTS_DOC, "utf8");
  } catch {
    return; // doc doesn't exist locally, nothing to update
  }

  doc = doc.replace(/<!-- LAST_RUN -->.*(?=\n)/, summaryLine);

  const marker = "## Run log";
  const idx = doc.indexOf(marker);
  if (idx !== -1) {
    const afterHeading = doc.indexOf("\n", idx) + 1;
    const nextLine = doc.slice(afterHeading).match(/^\(newest first.*\)\n?/);
    const insertAt = nextLine ? afterHeading + nextLine[0].length : afterHeading;
    doc = doc.slice(0, insertAt) + logLine + "\n" + doc.slice(insertAt);
  }

  await writeFile(REQUIREMENTS_DOC, doc, "utf8");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
